### PR TITLE
Mention Highlighting

### PR DESCRIPTION
**Pull request by SoeyFlamepaw**
Added a mention blend color setting, making Killroy highlight mentions of the characters First or Last Name, to make it easier to recognize when somebody talks to or interacts with you.

I made those changes for personal use, but I hope you'll include that into official Killroy, as others surely might find that useful as well :) I wrote a small guide for Killroy on wildstar-roleplay.com because it's the most awesome addon ever, and soon noticed something troubling: Many roleplayers are using the ChatLinks addon specifically for its mention-highlighting, but the combination of ChatLinks  and Killroy sadly silently breaks Killroy's chat formatting, ruining one of your most awesome features. Should you decide to include my changes, and any bugs arise from them, I'm sure AllyHarkens will poke me to near-death until I fix them, which I vow to do! :3

### CODE REVIEW

**Comment by baslack** [comment]
I don't have a problem with the addition. I'm not under sub currently to test it though. Please review it with Ally to confirm functionality with a few other users. Assuming all is good, she can increment the version put changes into the master. Thanks for your assistance with the project, Soey. It's appreciated.

**Comment by SoeyFlamepaw** [comment]
Of course, will do!

**Comment by Togglebutton** [comment]
I'll take a look at it later as well. Was considering forking to merge in
code from chatlinks anyway. Trying to get back to coding.

**Comment by SoeyFlamepaw** [comment]
Awesome!

Playing with it myself I noticed, while not causing any bugs so far, the mention highlighting does not always work. It works perfectly for regular /say or /emote text, but not for stuff that has its own special format, like "..." or *...* inside /say or /emote messages. So.. only halfway what I wanted to achieve. but that's probably just something about the order of those things being processed, I'd guess. I'll take another look later.

**Comment by Togglebutton** [comment]
Yes, you have to think outside in for order of formatting, so your name
highlighting should be after others.

**Pull request merged**
